### ISSUE TITLE
Image Submit doesn't work on first attempt

### ISSUE THREAD

**Issue by itsclarke** [firebase/friendlychat#104]
I've just completed the tutorial and noticed that nothing happens the first time I submit an image. However, once a "?#" is appended to the url and I attempt to submit an image a second time, it comes through fine (the second image appears, the first one seems to be lost/never makes it to the database).

https://chat-app-c3ea7.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
Hey @itsclarke I wanted to test now, sorry for the delay but it seems the app is now not working (looks like you were working on adding notifications in there). Let me know once you have a working app again and I'll be happy to have a look.

**Comment by svaldi** [comment]
Seems the issue is not in FF but it is still appearing on Chrome. 

Hello @nicolasgarnier 
To reproduce:
1. Go to: https://chat-app-c3ea7.firebaseapp.com/ **(Ingnore missing styles)**
2. Click on the Image button on the right side of the page. 
3. See the URL ("?#" will be added)

Test on FF and Chrome.

**Comment by nicolasgarnier** [comment]
Fixed!
