### ISSUE TITLE
Make communicate users mutually

### ISSUE THREAD

**Issue by lahssen** [firebase/friendlychat#142]
Hi everybody,
I started the first project of friendlychat, android-start, and all thing will done, now i want to complet this project to make communicate users mutually (user_1 with user_2 only no on group chat like first project).
can you help me, Is there any other google project can do that?

lahssen think you

**Comment by kroikie** [comment]
@lahssen This codelab creates a global "room" where all users can see all messages. However you can adjust it so that you create individual rooms for each conversation. So instead of:

- messages
    - msg_1
        ...
    - msg_2
        ...

You will have:
- conversations
    - conversation_1
        - msg_1
            ...
        - msg_2
            ...
    - conversation_2
        - msg_1
            ...
        - msg_2
            ...

Each conversation would only contain messages from the users that are in that conversation. You can use database rules to enforce these restrictions.
