### ISSUE TITLE
Error:Execution failed for task ':app:processReleaseGoogleServices'. > Missing api_key/current_key object

### ISSUE THREAD

**Issue by rajatsachan8** [firebase/friendlychat#143]
this error is shown when i tried to generate the apk.

**Comment by sejr** [comment]
This occurs because your generated `google-services.json` is missing the required API Key. Did you provide the SHA1 of your signing keystore when you created the application on the Firebase Console? If not, get the SHA1, add it to the Firebase app, then redownload the JSON file.

**Comment by samtstern** [comment]
We've seen a few cases of a race condition on the server causing the `google-services.json` file to not have the required `api_key/current_key` entry.  This should be fixed if you just re-download the file.

Also worth noting that since this issue was filed (Jan 12th) we've released a server-side fix so I am going to close this issue (as it should not happen anymore).
