### ISSUE TITLE
there is no sign in button in step 5

### ISSUE THREAD

**Issue by jameseraynor** [firebase/friendlychat#220]
hi,

in step 5 of the web tutorial (https://codelabs.developers.google.com/codelabs/firebase-web/#5) there is no sign in button to test if my changes are correct, see the code that they are hidden, but when I remove the hidden property nothing happens.

**Comment by dustincmeyer** [comment]
@jameseraynor - I'm not sure if this will solve you're issue, but it did for me. I had accidentally created a second `initFirebase` method instead of *modifying* the first. My code looked as such:

```
// Sets up shortcuts to Firebase features and initiate firebase auth
FriendlyChat.prototype.initFirebase = function() {
  // Shortcuts to Firebase SDK features.
  this.auth = firebase.auth();
  this.database = firebase.database();
  this.storage = firebase.storage();
  // Initiates Firebase auth and listen to auth state changes
  this.auth.onAuthStateChanged(this.onAuthStateChanged.bind(this));
}

// Sets up shortcuts to Firebase features and initiate firebase auth.
FriendlyChat.prototype.initFirebase = function() {
  // TODO(DEVELOPER): Initialize Firebase.
};
```

In essence, my modified changes were replaced by the second (and empty) method that I should have implemented. Also, keeping your console open will help point out any other errors.

Best of luck.

**Comment by jameseraynor** [comment]
it worked,  thanks

**Comment by kroikie** [comment]
Thanks @jameseraynor and @dustincmeyer I'm closing this issue now.
