### ISSUE TITLE
firebase serve error

### ISSUE THREAD

**Issue by kelokchan** [firebase/friendlychat#29]
I am following the instructions exactly but I'm getting this error.

[debug] ----------------------------------------------------------------------
[debug] Command:      C:\Program Files\nodejs\node.exe C:\Users\kuokkit.chan\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase serve
[debug] CLI Version:  3.0.0
[debug] Platform:     win32
[debug] Node Version: v4.4.4
[debug] Time:         Tue May 24 2016 09:53:03 GMT+0800 (Malay Peninsula Standard Time)
[debug] ----------------------------------------------------------------------
[debug] 
[info] Starting Firebase development server...
[info] 
[info] Project Directory: C:\Users\kuokkit.chan\Desktop\Firebase\friendlychat\web-start
[debug] TypeError: Cannot read property 'public' of undefined
    at Server.<anonymous> (C:\Users\kuokkit.chan\AppData\Roaming\npm\node_modules\firebase-tools\commands\serve.js:24:15)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
[error] 
[error] Error: An unexpected error has occurred.

Please help

**Comment by nicolasgarnier** [comment]
`[debug] TypeError: Cannot read property 'public' of undefined`

This means that there is no `hosting.public` attribute in the `firebase.json` file. It should have that see: https://github.com/firebase/friendlychat/blob/master/web-start/firebase.json (unless you checked out the code the first couple days of Google IO, we've fixed it since). Can you make sure you checkout the latest code from the GitHub repo?
