### ISSUE TITLE
FirebaseApiNotAvailableException

### ISSUE THREAD

**Issue by lawgimenez** [firebase/friendlychat#32]
Followed the tutorial **For Android** and after implementing the sign in/sign out, Firebase threw an exception like 
`com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.`

**Comment by kroikie** [comment]
This may be due to the device not having the latest version of Google Play services, what version does it have?

**Comment by javiexpo** [comment]
I have an error with the same Exception but with another detail, its said:
`com.google.firebase.FirebaseApiNotAvailableException: Error resolution was canceled by the user`

But, I am running my Firebase Android App in the Emulator, could be this the problem?, I mean because I am using the emulator instead of a device?

**Comment by kroikie** [comment]
I don't believe this is still an issue, closing. Please reopen is issue still exists.
